function mydialog(text1, text2)

d = dialog('Position',[300 300 250 150], 'Name', 'Result');

txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 80 210 40],...
    'String', text1);

txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[20 60 210 40],...
    'String', text2);

btn = uicontrol('Parent',d,...
    'Position',[85 20 70 25],...
    'String','Close',...
    'Callback','delete(gcf)');
end